### ISSUE TITLE
commanded.new is not working with Miro

### ISSUE THREAD

**Issue by parth-patil** [commanded/generator#1]
When I run
`mix commanded.new auctioneer --miro o9J_l9SPDEY=`

I get the following error
`
** (MatchError) no match of right hand side value: {:error, "No authorization data was found on the request"}
    (commanded_generator 1.2.0) lib/commanded/generator/project.ex:49: Commanded.Generator.Project.build_model/3
    (commanded_generator 1.2.0) lib/mix/tasks/commanded.new.ex:97: Mix.Tasks.Commanded.New.generate/4
    (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.4) lib/mix/cli.ex:84: Mix.CLI.run_task/2
`

**Comment by BasileNouvellet** [comment]
You might want to run the command with your Miro REST API access token as an env var:

```bash
MIRO_ACCESS_TOKEN=<your-access-token> mix commanded.new PATH --miro BOARD_ID
```

**Comment by quarterpi** [comment]
How did you get a token? Did you have to setup a developer team with Miro?

**Comment by jdewar** [comment]
> How did you get a token? Did you have to setup a developer team with Miro?

I just solved this mystery; yes you start up a dev team and more.  I followed this through step 4: https://developers.miro.com/docs/getting-started

**Comment by Exadra37** [comment]
> I just solved this mystery; yes you start up a dev team and more. I followed this through step 4: https://developers.miro.com/docs/getting-started

Doesn't seem possible without a paid plan, at least I am not able to create the dev team.
